// Runtime validators generated from the backend's OpenAPI document (../openapi/openapi.json).
// Types come from openapi-typescript (src/lib/api/schema.gen.ts); both are regenerated by
// `npm run gen:api` and checked for drift in CI.
import { readFileSync } from 'node:fs';
import { defineConfig } from '@hey-api/openapi-ts';

type Node = { [key: string]: unknown };

/**
 * The zod plugin coerces `format: int64` to BigInt, while openapi-typescript types those
 * fields as `number`. Every int64 in this API (ids, minor-unit amounts, counts) is far
 * inside Number.MAX_SAFE_INTEGER, so validate them as JS integers and keep types and
 * validators in agreement.
 */
function int64AsNumber(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(int64AsNumber);
  if (node && typeof node === 'object') {
    const out: Node = {};
    for (const [key, value] of Object.entries(node as Node)) {
      if (key === 'format' && value === 'int64') continue;
      out[key] = int64AsNumber(value);
    }
    return out;
  }
  return node;
}

const spec = JSON.parse(readFileSync('../openapi/openapi.json', 'utf8')) as Node;

export default defineConfig({
  input: int64AsNumber(spec) as Record<string, unknown>,
  output: { path: 'src/lib/api/zod', clean: true },
  plugins: [{ name: 'zod', compatibilityVersion: 3 }],
});
