// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAddItem = z.object({
    description: z.string(),
    quantity: z.string(),
    unit_price: z.number().int(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish()
});

export const zAddSuppression = z.object({
    email: z.string(),
    reason: z.string().nullish()
});

export const zAdminStatus = z.object({
    environment: z.string(),
    email_mode: z.string(),
    smtp_host: z.string().nullish(),
    email_redirect_to: z.string().nullish(),
    automatic_email_enabled: z.boolean(),
    failed_jobs: z.number().int(),
    pending_jobs: z.number().int(),
    emails_needing_attention: z.number().int(),
    orders_missing_fx_rate: z.number().int(),
    latest_eur_rate_day: z.string().date().nullish()
});

export const zAttachmentRef = z.object({
    document_id: z.number().int(),
    filename: z.string().nullish(),
    byte_size: z.number().int().nullish(),
    mode: z.string().nullish()
});

export const zAuditEntry = z.object({
    id: z.number().int(),
    at: z.string().datetime(),
    user_id: z.number().int().nullish(),
    user_name: z.string().nullish(),
    entity: z.string(),
    entity_id: z.number().int(),
    action: z.string(),
    changes: z.record(z.unknown())
});

export const zBlocker = z.object({
    id: z.number().int(),
    order_id: z.number().int(),
    order_number: z.string(),
    what: z.string(),
    responsible_partner_id: z.number().int().nullish(),
    responsible_partner_name: z.string().nullish(),
    responsible_email: z.string().nullish(),
    due_date: z.string().date().nullish(),
    notes: z.string().nullish(),
    nudge_enabled: z.boolean(),
    last_nudged_at: z.string().datetime().nullish(),
    nudge_count: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    resolved_at: z.string().datetime().nullish(),
    resolved_by: z.number().int().nullish(),
    resolution_note: z.string().nullish(),
    created_by: z.number().int().nullish(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    is_overdue: z.boolean()
});

/**
 * Create requires `what`. On PATCH every field is optional; `null` clears.
 */
export const zBlockerBody = z.object({
    what: z.string().nullish(),
    responsible_partner_id: z.number().int().nullish(),
    responsible_email: z.string().nullish(),
    due_date: z.string().date().nullish(),
    notes: z.string().nullish(),
    nudge_enabled: z.boolean().nullish()
});

export const zBlockerLoadRow = z.object({
    partner_id: z.number().int().nullish(),
    responsible: z.string(),
    blockers: z.number().int(),
    open: z.number().int(),
    overdue: z.number().int(),
    nudges: z.number().int(),
    waiting_days: z.number()
});

export const zBlockerLoadEntry = zBlockerLoadRow.and(z.object({
    share_of_waiting: z.number()
}));

export const zChangePasswordBody = z.object({
    current_password: z.string(),
    new_password: z.string()
});

export const zCompleteBody = z.object({
    ticket: z.string()
});

export const zComposeRequest = z.object({
    order_id: z.number().int().nullish(),
    lead_id: z.number().int().nullish(),
    partner_id: z.number().int().nullish(),
    to: z.string(),
    cc: z.array(z.string()).optional(),
    template_key: z.string().nullish(),
    subject: z.string().nullish(),
    body: z.string().nullish(),
    attachment_document_ids: z.array(z.number().int()).optional()
});

export const zContact = z.object({
    id: z.number().int(),
    partner_id: z.number().int(),
    name: z.string(),
    email: z.string().nullish(),
    phone: z.string().nullish(),
    position: z.string().nullish(),
    notes: z.string().nullish(),
    archived_at: z.string().datetime().nullish(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

/**
 * Create requires `name`. On PATCH every field is optional; `null` clears.
 */
export const zContactBody = z.object({
    name: z.string().nullish(),
    email: z.string().nullish(),
    phone: z.string().nullish(),
    position: z.string().nullish(),
    notes: z.string().nullish()
});

export const zCreateProjectType = z.object({
    key: z.string(),
    label_hu: z.string(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zCreateTemplate = z.object({
    key: z.string(),
    name: z.string(),
    subject: z.string(),
    body: z.string()
});

export const zCurrency = z.enum(['HUF', 'EUR']);

export const zCurrentStage = z.object({
    stage_key: z.string(),
    entered_at: z.string().datetime()
});

export const zDocumentKind = z.enum([
    'design',
    'cad',
    'other'
]);

export const zDocument = z.object({
    id: z.number().int(),
    order_id: z.number().int(),
    kind: zDocumentKind,
    filename: z.string(),
    content_type: z.string(),
    content_hash: z.string(),
    byte_size: z.number().int(),
    uploaded_at: z.string().datetime(),
    uploaded_by: z.number().int().nullish(),
    deleted_at: z.string().datetime().nullish()
});

export const zDownloadUrl = z.object({
    url: z.string()
});

export const zEmailStatus = z.enum([
    'queued',
    'sending',
    'sent',
    'failed',
    'cancelled',
    'needs_review'
]);

export const zEmailMessage = z.object({
    id: z.number().int(),
    order_id: z.number().int().nullish(),
    lead_id: z.number().int().nullish(),
    partner_id: z.number().int().nullish(),
    blocker_id: z.number().int().nullish(),
    template_key: z.string().nullish(),
    trigger: z.string(),
    is_automatic: z.boolean(),
    sent_by: z.number().int().nullish(),
    to_address: z.string(),
    cc: z.array(z.string()),
    from_address: z.string(),
    reply_to: z.string().nullish(),
    subject: z.string(),
    body_html: z.string(),
    body_text: z.string(),
    attachments: z.array(zAttachmentRef),
    status: zEmailStatus,
    provider_id: z.string().nullish(),
    error: z.string().nullish(),
    attempts: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    queued_at: z.string().datetime(),
    send_after: z.string().datetime(),
    sending_started_at: z.string().datetime().nullish(),
    sent_at: z.string().datetime().nullish(),
    cancelled_at: z.string().datetime().nullish(),
    cancelled_by: z.number().int().nullish()
});

/**
 * List view: everything except the bodies.
 */
export const zEmailSummary = z.object({
    id: z.number().int(),
    order_id: z.number().int().nullish(),
    lead_id: z.number().int().nullish(),
    partner_id: z.number().int().nullish(),
    blocker_id: z.number().int().nullish(),
    template_key: z.string().nullish(),
    trigger: z.string(),
    is_automatic: z.boolean(),
    sent_by: z.number().int().nullish(),
    sent_by_name: z.string().nullish(),
    to_address: z.string(),
    subject: z.string(),
    status: zEmailStatus,
    error: z.string().nullish(),
    queued_at: z.string().datetime(),
    send_after: z.string().datetime(),
    sent_at: z.string().datetime().nullish()
});

export const zEmailTemplate = z.object({
    id: z.number().int(),
    key: z.string(),
    name: z.string(),
    subject: z.string(),
    body: z.string(),
    locale: z.string(),
    is_automatic: z.boolean(),
    updated_at: z.string().datetime(),
    updated_by: z.number().int().nullish()
});

/**
 * A candidate transport for the test endpoint. Same validation as saving;
 * `smtp_password` absent falls back to the saved secret so hosts can be
 * retried without retyping it. Nothing here is persisted.
 */
export const zEmailTestCandidate = z.object({
    mode: z.string(),
    smtp_host: z.string().nullish(),
    smtp_port: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    smtp_security: z.string().nullish(),
    smtp_username: z.string().nullish(),
    smtp_password: z.string().nullish(),
    smtp_helo_name: z.string().nullish(),
    smtp_force_ipv4: z.boolean().nullish(),
    redirect_to: z.string().nullish()
});

export const zEmailTestBody = z.object({
    to: z.string(),
    config: zEmailTestCandidate.nullish()
});

export const zEmailTestResult = z.object({
    ok: z.boolean(),
    detail: z.string()
});

/**
 * Email transport overrides. Every field is optional: absent keeps the stored
 * value, explicit null returns it to "inherit from the environment".
 * `mode: null` clears the whole transport back to environment behaviour.
 * `smtp_password`: absent keeps, null clears, a value replaces. Blank
 * strings are treated as absent everywhere (never a destructive surprise).
 */
export const zEmailTransportBody = z.object({
    mode: z.string().nullish(),
    smtp_host: z.string().nullish(),
    smtp_port: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    smtp_security: z.string().nullish(),
    smtp_username: z.string().nullish(),
    smtp_password: z.string().nullish(),
    smtp_helo_name: z.string().nullish(),
    smtp_force_ipv4: z.boolean().nullish(),
    redirect_to: z.string().nullish()
});

export const zErrorDetail = z.object({
    code: z.string(),
    message: z.string()
});

/**
 * The body of every non-2xx response.
 */
export const zErrorBody = z.object({
    error: zErrorDetail
});

export const zFxFetch = z.object({
    from: z.string().date(),
    to: z.string().date()
});

export const zFxRate = z.object({
    day: z.string().date(),
    base: z.string(),
    quote: z.string(),
    rate: z.string(),
    source: z.string(),
    fetched_at: z.string().datetime()
});

export const zImageCategory = z.enum([
    'intake',
    'production',
    'completion',
    'marketing'
]);

export const zImage = z.object({
    id: z.number().int(),
    order_id: z.number().int(),
    category: zImageCategory,
    content_type: z.string(),
    original_filename: z.string().nullish(),
    content_hash: z.string(),
    byte_size: z.number().int(),
    width: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    height: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    captured_at: z.string().datetime().nullish(),
    processed_at: z.string().datetime().nullish(),
    processing_error: z.string().nullish(),
    uploaded_at: z.string().datetime(),
    uploaded_by: z.number().int().nullish(),
    immutable: z.boolean(),
    deleted_at: z.string().datetime().nullish()
});

export const zCompleted = z.union([
    z.object({
        image: zImage,
        created: z.boolean(),
        type: z.enum(['image'])
    }),
    z.object({
        document: zDocument,
        created: z.boolean(),
        type: z.enum(['document'])
    })
]);

export const zImageView = zImage.and(z.object({
    thumb_url: z.string().nullish(),
    display_url: z.string().nullish()
}));

export const zItemBody = z.object({
    description: z.string(),
    quantity: z.string(),
    unit_price: z.number().int()
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsAuditEntry = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        at: z.string().datetime(),
        user_id: z.number().int().nullish(),
        user_name: z.string().nullish(),
        entity: z.string(),
        entity_id: z.number().int(),
        action: z.string(),
        changes: z.record(z.unknown())
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsBlocker = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        order_id: z.number().int(),
        order_number: z.string(),
        what: z.string(),
        responsible_partner_id: z.number().int().nullish(),
        responsible_partner_name: z.string().nullish(),
        responsible_email: z.string().nullish(),
        due_date: z.string().date().nullish(),
        notes: z.string().nullish(),
        nudge_enabled: z.boolean(),
        last_nudged_at: z.string().datetime().nullish(),
        nudge_count: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
        resolved_at: z.string().datetime().nullish(),
        resolved_by: z.number().int().nullish(),
        resolution_note: z.string().nullish(),
        created_by: z.number().int().nullish(),
        created_at: z.string().datetime(),
        updated_at: z.string().datetime(),
        is_overdue: z.boolean()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsContact = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        partner_id: z.number().int(),
        name: z.string(),
        email: z.string().nullish(),
        phone: z.string().nullish(),
        position: z.string().nullish(),
        notes: z.string().nullish(),
        archived_at: z.string().datetime().nullish(),
        created_at: z.string().datetime(),
        updated_at: z.string().datetime()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsDocument = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        order_id: z.number().int(),
        kind: zDocumentKind,
        filename: z.string(),
        content_type: z.string(),
        content_hash: z.string(),
        byte_size: z.number().int(),
        uploaded_at: z.string().datetime(),
        uploaded_by: z.number().int().nullish(),
        deleted_at: z.string().datetime().nullish()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsEmailSummary = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        order_id: z.number().int().nullish(),
        lead_id: z.number().int().nullish(),
        partner_id: z.number().int().nullish(),
        blocker_id: z.number().int().nullish(),
        template_key: z.string().nullish(),
        trigger: z.string(),
        is_automatic: z.boolean(),
        sent_by: z.number().int().nullish(),
        sent_by_name: z.string().nullish(),
        to_address: z.string(),
        subject: z.string(),
        status: zEmailStatus,
        error: z.string().nullish(),
        queued_at: z.string().datetime(),
        send_after: z.string().datetime(),
        sent_at: z.string().datetime().nullish()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsEmailTemplate = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        key: z.string(),
        name: z.string(),
        subject: z.string(),
        body: z.string(),
        locale: z.string(),
        is_automatic: z.boolean(),
        updated_at: z.string().datetime(),
        updated_by: z.number().int().nullish()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsFxRate = z.object({
    items: z.array(z.object({
        day: z.string().date(),
        base: z.string(),
        quote: z.string(),
        rate: z.string(),
        source: z.string(),
        fetched_at: z.string().datetime()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsImageView = z.object({
    items: z.array(zImage.and(z.object({
        thumb_url: z.string().nullish(),
        display_url: z.string().nullish()
    })))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsJob = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        kind: z.string(),
        payload: z.record(z.unknown()),
        dedupe_key: z.string().nullish(),
        run_at: z.string().datetime(),
        attempts: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
        max_attempts: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
        locked_at: z.string().datetime().nullish(),
        locked_by: z.string().nullish(),
        completed_at: z.string().datetime().nullish(),
        failed_at: z.string().datetime().nullish(),
        last_error: z.string().nullish(),
        created_at: z.string().datetime()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsLeadSummary = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        title: z.string(),
        partner_id: z.number().int().nullish(),
        partner_name: z.string().nullish(),
        contact_name: z.string().nullish(),
        contact_email: z.string().nullish(),
        source: z.string().nullish(),
        assigned_to: z.number().int().nullish(),
        assigned_name: z.string().nullish(),
        stage_key: z.string(),
        stage_label: z.string(),
        stage_entered_at: z.string().datetime(),
        order_id: z.number().int().nullish(),
        order_number: z.string().nullish(),
        created_at: z.string().datetime()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsOrderSummary = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        number: z.string(),
        title: z.string(),
        partner_id: z.number().int(),
        partner_name: z.string(),
        project_type_id: z.number().int().nullish(),
        project_type_label: z.string().nullish(),
        currency: zCurrency,
        total_minor: z.number().int(),
        vehicle_make: z.string().nullish(),
        vehicle_model: z.string().nullish(),
        vehicle_plate: z.string().nullish(),
        due_date: z.string().date().nullish(),
        assigned_to: z.number().int().nullish(),
        assigned_name: z.string().nullish(),
        stage_key: z.string(),
        stage_label: z.string(),
        stage_is_terminal: z.boolean(),
        stage_entered_at: z.string().datetime(),
        open_blockers: z.number().int(),
        created_at: z.string().datetime(),
        updated_at: z.string().datetime()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsPickerOrder = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        number: z.string(),
        title: z.string(),
        partner_name: z.string(),
        vehicle: z.string().nullish(),
        vehicle_plate: z.string().nullish(),
        stage_key: z.string(),
        stage_label: z.string()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsProjectType = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        key: z.string(),
        label_hu: z.string(),
        position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
        is_active: z.boolean()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsStageEntry = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        stage_key: z.string(),
        label_hu: z.string(),
        entered_at: z.string().datetime(),
        left_at: z.string().datetime().nullish(),
        entered_by: z.number().int().nullish(),
        entered_by_name: z.string().nullish(),
        note: z.string().nullish()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsStalledOrder = z.object({
    items: z.array(z.object({
        order_id: z.number().int(),
        number: z.string(),
        title: z.string(),
        partner_name: z.string(),
        stage_key: z.string(),
        stage_label: z.string(),
        entered_at: z.string().datetime(),
        days_in_stage: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
        stall_after_days: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
        open_blockers: z.number().int()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsSuppression = z.object({
    items: z.array(z.object({
        email: z.string(),
        reason: z.string().nullish(),
        created_at: z.string().datetime(),
        created_by: z.number().int().nullish()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsTemplateVariable = z.object({
    items: z.array(z.object({
        name: z.string(),
        description: z.string()
    }))
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsTransitionOption = z.object({
    items: z.array(z.object({
        stage_key: z.string(),
        label_hu: z.string(),
        manual: z.boolean(),
        requires_note: z.boolean(),
        gates_met: z.boolean()
    }))
});

export const zJob = z.object({
    id: z.number().int(),
    kind: z.string(),
    payload: z.record(z.unknown()),
    dedupe_key: z.string().nullish(),
    run_at: z.string().datetime(),
    attempts: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    max_attempts: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    locked_at: z.string().datetime().nullish(),
    locked_by: z.string().nullish(),
    completed_at: z.string().datetime().nullish(),
    failed_at: z.string().datetime().nullish(),
    last_error: z.string().nullish(),
    created_at: z.string().datetime()
});

export const zJobQueued = z.object({
    job_id: z.number().int().nullish()
});

export const zLead = z.object({
    id: z.number().int(),
    title: z.string(),
    partner_id: z.number().int().nullish(),
    contact_id: z.number().int().nullish(),
    contact_name: z.string().nullish(),
    contact_email: z.string().nullish(),
    contact_phone: z.string().nullish(),
    source: z.string().nullish(),
    description: z.string().nullish(),
    assigned_to: z.number().int().nullish(),
    created_by: z.number().int().nullish(),
    minicrm_id: z.number().int().nullish(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

/**
 * Create requires `title`. On PATCH every field is optional; `null` clears.
 */
export const zLeadBody = z.object({
    title: z.string().nullish(),
    partner_id: z.number().int().nullish(),
    contact_id: z.number().int().nullish(),
    contact_name: z.string().nullish(),
    contact_email: z.string().nullish(),
    contact_phone: z.string().nullish(),
    source: z.string().nullish(),
    description: z.string().nullish(),
    assigned_to: z.number().int().nullish()
});

export const zLeadSummary = z.object({
    id: z.number().int(),
    title: z.string(),
    partner_id: z.number().int().nullish(),
    partner_name: z.string().nullish(),
    contact_name: z.string().nullish(),
    contact_email: z.string().nullish(),
    source: z.string().nullish(),
    assigned_to: z.number().int().nullish(),
    assigned_name: z.string().nullish(),
    stage_key: z.string(),
    stage_label: z.string(),
    stage_entered_at: z.string().datetime(),
    order_id: z.number().int().nullish(),
    order_number: z.string().nullish(),
    created_at: z.string().datetime()
});

export const zOrder = z.object({
    id: z.number().int(),
    number: z.string(),
    title: z.string(),
    partner_id: z.number().int(),
    contact_id: z.number().int().nullish(),
    lead_id: z.number().int().nullish(),
    project_type_id: z.number().int().nullish(),
    currency: zCurrency,
    valuation_date: z.string().date(),
    vehicle_make: z.string().nullish(),
    vehicle_model: z.string().nullish(),
    vehicle_plate: z.string().nullish(),
    vehicle_vin: z.string().nullish(),
    description: z.string().nullish(),
    due_date: z.string().date().nullish(),
    assigned_to: z.number().int().nullish(),
    created_by: z.number().int().nullish(),
    minicrm_id: z.number().int().nullish(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zOrderBody = z.object({
    title: z.string().nullish(),
    partner_id: z.number().int().nullish(),
    contact_id: z.number().int().nullish(),
    project_type_id: z.number().int().nullish(),
    currency: zCurrency,
    valuation_date: z.string().date().nullish(),
    vehicle_make: z.string().nullish(),
    vehicle_model: z.string().nullish(),
    vehicle_plate: z.string().nullish(),
    vehicle_vin: z.string().nullish(),
    description: z.string().nullish(),
    due_date: z.string().date().nullish(),
    assigned_to: z.number().int().nullish(),
    items: z.array(zItemBody).optional()
});

export const zOrderItem = z.object({
    id: z.number().int(),
    order_id: z.number().int(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    description: z.string(),
    quantity: z.string(),
    unit_price: z.number().int(),
    currency: zCurrency,
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zItemView = zOrderItem.and(z.object({
    line_total_minor: z.number().int()
}));

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsItemView = z.object({
    items: z.array(zOrderItem.and(z.object({
        line_total_minor: z.number().int()
    })))
});

export const zOrderRef = z.object({
    id: z.number().int(),
    number: z.string()
});

export const zOrderSummary = z.object({
    id: z.number().int(),
    number: z.string(),
    title: z.string(),
    partner_id: z.number().int(),
    partner_name: z.string(),
    project_type_id: z.number().int().nullish(),
    project_type_label: z.string().nullish(),
    currency: zCurrency,
    total_minor: z.number().int(),
    vehicle_make: z.string().nullish(),
    vehicle_model: z.string().nullish(),
    vehicle_plate: z.string().nullish(),
    due_date: z.string().date().nullish(),
    assigned_to: z.number().int().nullish(),
    assigned_name: z.string().nullish(),
    stage_key: z.string(),
    stage_label: z.string(),
    stage_is_terminal: z.boolean(),
    stage_entered_at: z.string().datetime(),
    open_blockers: z.number().int(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zOrderValue = z.object({
    currency: zCurrency,
    total_minor: z.number().int(),
    valuation_date: z.string().date(),
    fx_day: z.string().date().nullish(),
    fx_rate: z.string().nullish(),
    total_huf_minor: z.number().int().nullish()
});

export const zOriginalImageUrl = z.object({
    url: z.string(),
    sha256: z.string()
});

export const zPartnerKind = z.enum(['business', 'person']);

export const zCreatePartner = z.object({
    kind: zPartnerKind,
    name: z.string(),
    tax_number: z.string().nullish(),
    eu_tax_number: z.string().nullish(),
    country: z.string().nullish(),
    default_currency: zCurrency.nullish(),
    email: z.string().nullish(),
    phone: z.string().nullish(),
    website: z.string().nullish(),
    postal_code: z.string().nullish(),
    city: z.string().nullish(),
    address_line: z.string().nullish(),
    notes: z.string().nullish()
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsPartner = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        kind: zPartnerKind,
        name: z.string(),
        tax_number: z.string().nullish(),
        eu_tax_number: z.string().nullish(),
        country: z.string(),
        default_currency: zCurrency,
        email: z.string().nullish(),
        phone: z.string().nullish(),
        website: z.string().nullish(),
        postal_code: z.string().nullish(),
        city: z.string().nullish(),
        address_line: z.string().nullish(),
        notes: z.string().nullish(),
        minicrm_id: z.number().int().nullish(),
        archived_at: z.string().datetime().nullish(),
        created_at: z.string().datetime(),
        updated_at: z.string().datetime()
    }))
});

export const zPartner = z.object({
    id: z.number().int(),
    kind: zPartnerKind,
    name: z.string(),
    tax_number: z.string().nullish(),
    eu_tax_number: z.string().nullish(),
    country: z.string(),
    default_currency: zCurrency,
    email: z.string().nullish(),
    phone: z.string().nullish(),
    website: z.string().nullish(),
    postal_code: z.string().nullish(),
    city: z.string().nullish(),
    address_line: z.string().nullish(),
    notes: z.string().nullish(),
    minicrm_id: z.number().int().nullish(),
    archived_at: z.string().datetime().nullish(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zPartnerDetail = z.object({
    partner: zPartner,
    contacts: z.array(zContact),
    orders: z.array(zOrderSummary)
});

export const zPartnerRef = z.object({
    id: z.number().int(),
    name: z.string()
});

export const zPatchItem = z.object({
    description: z.string().nullish(),
    quantity: z.string().nullish(),
    unit_price: z.number().int().nullish(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish()
});

export const zPatchOrder = z.object({
    title: z.string().nullish(),
    partner_id: z.number().int().nullish(),
    contact_id: z.number().int().nullish(),
    project_type_id: z.number().int().nullish(),
    currency: zCurrency.nullish(),
    valuation_date: z.string().date().nullish(),
    vehicle_make: z.string().nullish(),
    vehicle_model: z.string().nullish(),
    vehicle_plate: z.string().nullish(),
    vehicle_vin: z.string().nullish(),
    description: z.string().nullish(),
    due_date: z.string().date().nullish(),
    assigned_to: z.number().int().nullish()
});

export const zPatchPartner = z.object({
    kind: zPartnerKind.nullish(),
    name: z.string().nullish(),
    tax_number: z.string().nullish(),
    eu_tax_number: z.string().nullish(),
    country: z.string().nullish(),
    default_currency: zCurrency.nullish(),
    email: z.string().nullish(),
    phone: z.string().nullish(),
    website: z.string().nullish(),
    postal_code: z.string().nullish(),
    city: z.string().nullish(),
    address_line: z.string().nullish(),
    notes: z.string().nullish()
});

export const zPatchProjectType = z.object({
    label_hu: z.string().nullish(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    is_active: z.boolean().nullish()
});

export const zPatchStage = z.object({
    label_hu: z.string().nullish(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    min_images: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    required_image_category: zImageCategory.nullish(),
    stall_after_days: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    is_active: z.boolean().nullish()
});

export const zPatchTemplate = z.object({
    name: z.string().nullish(),
    subject: z.string().nullish(),
    body: z.string().nullish()
});

export const zPeriod = z.object({
    from: z.string().date(),
    to: z.string().date()
});

export const zBlockerLoadReport = z.object({
    period: zPeriod,
    total_waiting_days: z.number(),
    rows: z.array(zBlockerLoadEntry)
});

export const zPickerOrder = z.object({
    id: z.number().int(),
    number: z.string(),
    title: z.string(),
    partner_name: z.string(),
    vehicle: z.string().nullish(),
    vehicle_plate: z.string().nullish(),
    stage_key: z.string(),
    stage_label: z.string()
});

export const zPreferencesBody = z.object({
    density: z.string().nullish(),
    page_size: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish()
});

/**
 * A request the client must perform exactly as described: every header listed is signed.
 */
export const zPresignedRequest = z.object({
    method: z.string(),
    url: z.string(),
    headers: z.array(z.array(z.string()))
});

export const zPreview = z.object({
    to: z.string(),
    cc: z.array(z.string()),
    subject: z.string(),
    body_text: z.string(),
    body_html: z.string(),
    unresolved: z.array(z.string()),
    recipient_suppressed: z.boolean(),
    attachments: z.array(zAttachmentRef)
});

export const zProjectType = z.object({
    id: z.number().int(),
    key: z.string(),
    label_hu: z.string(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    is_active: z.boolean()
});

export const zResetPassword = z.object({
    temporary_password: z.string()
});

export const zResolveBody = z.object({
    note: z.string().nullish()
});

export const zRevokedSessions = z.object({
    revoked: z.number().int().gte(0)
});

export const zRole = z.enum([
    'admin',
    'office',
    'designer',
    'viewer'
]);

export const zCreateUser = z.object({
    email: z.string(),
    display_name: z.string(),
    role: zRole,
    temporary_password: z.string()
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsUser = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        email: z.string(),
        display_name: z.string(),
        role: zRole,
        is_active: z.boolean(),
        must_change_password: z.boolean(),
        created_at: z.string().datetime(),
        updated_at: z.string().datetime()
    }))
});

export const zSessionKind = z.enum(['web', 'mobile']);

export const zLoginBody = z.object({
    email: z.string(),
    password: z.string(),
    client: zSessionKind.optional(),
    device_label: z.string().nullish()
});

export const zSessionInfo = z.object({
    id: z.number().int(),
    kind: zSessionKind,
    device_label: z.string().nullish(),
    user_agent: z.string().nullish(),
    ip: z.string().nullish(),
    created_at: z.string().datetime(),
    last_seen_at: z.string().datetime(),
    expires_at: z.string().datetime()
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsSessionView = z.object({
    items: z.array(zSessionInfo.and(z.object({
        current: z.boolean()
    })))
});

/**
 * The signed-in user as clients see it. Login and `/auth/me` return the same shape.
 */
export const zSessionUser = z.object({
    id: z.number().int(),
    email: z.string(),
    display_name: z.string(),
    role: zRole,
    must_change_password: z.boolean(),
    session_kind: zSessionKind
});

export const zLoginResponse = z.object({
    user: zSessionUser,
    token: z.string().nullish(),
    expires_at: z.string().datetime().nullish()
});

export const zMeResponse = z.object({
    user: zSessionUser
});

export const zSessionView = zSessionInfo.and(z.object({
    current: z.boolean()
}));

export const zSettings = z.object({
    automatic_email_enabled: z.boolean(),
    max_auto_emails_per_recipient_day: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    send_window_start: z.string(),
    send_window_end: z.string(),
    send_window_weekdays_only: z.boolean(),
    nudge_interval_days: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    nudge_escalate_after: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    stage_change_notifications: z.boolean(),
    stalled_alert_recipients: z.array(z.string()),
    updated_at: z.string().datetime(),
    updated_by: z.number().int().nullish(),
    email_mode: z.string().nullish(),
    smtp_host: z.string().nullish(),
    smtp_port: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    smtp_security: z.string().nullish(),
    smtp_username: z.string().nullish(),
    has_password: z.boolean(),
    smtp_helo_name: z.string().nullish(),
    smtp_force_ipv4: z.boolean().nullish(),
    redirect_to: z.string().nullish()
});

export const zSettingsBody = z.object({
    automatic_email_enabled: z.boolean(),
    max_auto_emails_per_recipient_day: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    send_window_start: z.string(),
    send_window_end: z.string(),
    send_window_weekdays_only: z.boolean(),
    nudge_interval_days: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    nudge_escalate_after: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    stage_change_notifications: z.boolean(),
    stalled_alert_recipients: z.array(z.string()).optional(),
    email: zEmailTransportBody.optional()
});

export const zStageBody = z.object({
    stage: z.string(),
    note: z.string().nullish()
});

export const zStageDurationRow = z.object({
    stage_key: z.string(),
    label: z.string(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    visits: z.number().int(),
    currently_in_stage: z.number().int(),
    avg_days: z.number().nullish(),
    median_days: z.number().nullish(),
    p90_days: z.number().nullish()
});

export const zDurationReport = z.object({
    period: zPeriod,
    rows: z.array(zStageDurationRow)
});

export const zStageEntity = z.enum(['lead', 'order']);

export const zCreateStage = z.object({
    entity: zStageEntity,
    key: z.string(),
    label_hu: z.string(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    min_images: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    required_image_category: zImageCategory.nullish(),
    is_terminal: z.boolean().optional(),
    is_exit: z.boolean().optional(),
    stall_after_days: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish()
});

/**
 * The list envelope: `{"items": [...]}`.
 */
export const zItemsStageDefinition = z.object({
    items: z.array(z.object({
        id: z.number().int(),
        entity: zStageEntity,
        key: z.string(),
        label_hu: z.string(),
        position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
        min_images: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
        required_image_category: zImageCategory.nullish(),
        is_terminal: z.boolean(),
        is_exit: z.boolean(),
        stall_after_days: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
        is_active: z.boolean()
    }))
});

export const zStageDefinition = z.object({
    id: z.number().int(),
    entity: zStageEntity,
    key: z.string(),
    label_hu: z.string(),
    position: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    min_images: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    required_image_category: zImageCategory.nullish(),
    is_terminal: z.boolean(),
    is_exit: z.boolean(),
    stall_after_days: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    is_active: z.boolean()
});

export const zStageEntry = z.object({
    id: z.number().int(),
    stage_key: z.string(),
    label_hu: z.string(),
    entered_at: z.string().datetime(),
    left_at: z.string().datetime().nullish(),
    entered_by: z.number().int().nullish(),
    entered_by_name: z.string().nullish(),
    note: z.string().nullish()
});

export const zLeadDetail = z.object({
    lead: zLead,
    stage: zCurrentStage.nullish(),
    history: z.array(zStageEntry),
    order: zOrderRef.nullish()
});

export const zStageView = z.object({
    key: z.string(),
    label_hu: z.string(),
    entered_at: z.string().datetime(),
    days_in_stage: z.number().int(),
    is_terminal: z.boolean()
});

export const zOrderDetail = z.object({
    order: zOrder,
    partner: zPartnerRef,
    stage: zStageView,
    items: z.array(zItemView),
    value: zOrderValue,
    blockers: z.array(zBlocker),
    image_counts: z.record(z.number().int())
});

export const zStalledOrder = z.object({
    order_id: z.number().int(),
    number: z.string(),
    title: z.string(),
    partner_name: z.string(),
    stage_key: z.string(),
    stage_label: z.string(),
    entered_at: z.string().datetime(),
    days_in_stage: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    stall_after_days: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    open_blockers: z.number().int()
});

export const zSuppression = z.object({
    email: z.string(),
    reason: z.string().nullish(),
    created_at: z.string().datetime(),
    created_by: z.number().int().nullish()
});

export const zTemplateVariable = z.object({
    name: z.string(),
    description: z.string()
});

export const zThroughputRow = z.object({
    period: z.string(),
    completed: z.number().int(),
    median_lead_days: z.number().nullish(),
    avg_lead_days: z.number().nullish()
});

export const zThroughputReport = z.object({
    period: zPeriod,
    rows: z.array(zThroughputRow)
});

export const zTransitionKind = z.enum([
    'forward',
    'backward',
    'exit',
    'reopen'
]);

export const zStageChange = z.object({
    from: z.string(),
    to: z.string(),
    kind: zTransitionKind
});

/**
 * One manual stage target, with everything the UI needs to present it
 * without reimplementing the transition rules: whether a hand move there is
 * allowed at all, whether it needs a note, and whether its image gates pass.
 * Computed from the same `check_transition` the move itself goes through.
 */
export const zTransitionOption = z.object({
    stage_key: z.string(),
    label_hu: z.string(),
    manual: z.boolean(),
    requires_note: z.boolean(),
    gates_met: z.boolean()
});

export const zUpdateUser = z.object({
    display_name: z.string().nullish(),
    role: zRole.nullish(),
    is_active: z.boolean().nullish()
});

export const zUploadResponse = z.union([
    z.object({
        ticket: z.string(),
        upload: zPresignedRequest,
        expires_at: z.string().datetime(),
        status: z.enum(['upload'])
    }),
    z.object({
        image_id: z.number().int().nullish(),
        document_id: z.number().int().nullish(),
        status: z.enum(['already_uploaded'])
    })
]);

export const zUploadTarget = z.union([
    z.object({
        category: zImageCategory,
        type: z.enum(['image'])
    }),
    z.object({
        kind: zDocumentKind,
        type: z.enum(['document'])
    })
]);

export const zUploadRequest = z.object({
    target: zUploadTarget,
    filename: z.string().nullish(),
    content_type: z.string(),
    byte_size: z.number().int(),
    sha256: z.string()
});

export const zUser = z.object({
    id: z.number().int(),
    email: z.string(),
    display_name: z.string(),
    role: zRole,
    is_active: z.boolean(),
    must_change_password: z.boolean(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zUserSettings = z.object({
    user_id: z.number().int(),
    density: z.string(),
    page_size: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    updated_at: z.string().datetime()
});

export const zVolumeRow = z.object({
    key: z.string(),
    label: z.string(),
    orders: z.number().int(),
    huf_minor: z.number().int(),
    eur_minor: z.number().int(),
    normalized_huf_minor: z.number().int(),
    missing_fx: z.number().int()
});

export const zVolumeReport = z.object({
    period: zPeriod,
    group: z.string(),
    rows: z.array(zVolumeRow),
    totals: zVolumeRow
});

export const zAuthLoginBody = zLoginBody;

/**
 * Signed in. Web clients also receive the httpOnly `autocrm_session` cookie.
 */
export const zAuthLoginResponse = zLoginResponse;

/**
 * Current session revoked
 */
export const zAuthLogoutResponse = z.void();

export const zAuthMeResponse = zMeResponse;

export const zAuthChangePasswordBody = zChangePasswordBody;

/**
 * Password changed; other sessions revoked
 */
export const zAuthChangePasswordResponse = z.void();

export const zAuthListSessionsResponse = zItemsSessionView;

export const zAuthRevokeSessionPath = z.object({
    id: z.number().int()
});

/**
 * Session revoked
 */
export const zAuthRevokeSessionResponse = z.void();

/**
 * Own preferences; defaults when never saved
 */
export const zAuthGetPreferencesResponse = zUserSettings;

export const zAuthPutPreferencesBody = zPreferencesBody;

export const zAuthPutPreferencesResponse = zUserSettings;

export const zUsersListResponse = zItemsUser;

export const zUsersCreateBody = zCreateUser;

export const zUsersCreateResponse = zUser;

export const zUsersUpdateBody = zUpdateUser;

export const zUsersUpdatePath = z.object({
    id: z.number().int()
});

export const zUsersUpdateResponse = zUser;

export const zUsersResetPasswordBody = zResetPassword;

export const zUsersResetPasswordPath = z.object({
    id: z.number().int()
});

/**
 * Password reset; the user must change it at next login
 */
export const zUsersResetPasswordResponse = z.void();

export const zUsersRevokeSessionsPath = z.object({
    id: z.number().int()
});

export const zUsersRevokeSessionsResponse = zRevokedSessions;

export const zConfigurationListStagesQuery = z.object({
    entity: zStageEntity.optional()
});

export const zConfigurationListStagesResponse = zItemsStageDefinition;

export const zConfigurationCreateStageBody = zCreateStage;

export const zConfigurationCreateStageResponse = zStageDefinition;

export const zConfigurationUpdateStageBody = zPatchStage;

export const zConfigurationUpdateStagePath = z.object({
    id: z.number().int()
});

export const zConfigurationUpdateStageResponse = zStageDefinition;

export const zConfigurationListProjectTypesResponse = zItemsProjectType;

export const zConfigurationCreateProjectTypeBody = zCreateProjectType;

export const zConfigurationCreateProjectTypeResponse = zProjectType;

export const zConfigurationUpdateProjectTypeBody = zPatchProjectType;

export const zConfigurationUpdateProjectTypePath = z.object({
    id: z.number().int()
});

export const zConfigurationUpdateProjectTypeResponse = zProjectType;

export const zConfigurationGetSettingsResponse = zSettings;

export const zConfigurationPutSettingsBody = zSettingsBody;

export const zConfigurationPutSettingsResponse = zSettings;

export const zPartnersSearchQuery = z.object({
    q: z.string().optional(),
    kind: zPartnerKind.optional(),
    include_archived: z.boolean().optional(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional()
});

export const zPartnersSearchResponse = zItemsPartner;

export const zPartnersCreateBody = zCreatePartner;

export const zPartnersCreateResponse = zPartner;

export const zPartnersDetailPath = z.object({
    id: z.number().int()
});

export const zPartnersDetailResponse = zPartnerDetail;

export const zPartnersUpdateBody = zPatchPartner;

export const zPartnersUpdatePath = z.object({
    id: z.number().int()
});

export const zPartnersUpdateResponse = zPartner;

export const zPartnersArchivePath = z.object({
    id: z.number().int()
});

/**
 * Archived
 */
export const zPartnersArchiveResponse = z.void();

export const zPartnersUnarchivePath = z.object({
    id: z.number().int()
});

/**
 * Restored
 */
export const zPartnersUnarchiveResponse = z.void();

export const zPartnersListContactsPath = z.object({
    id: z.number().int()
});

export const zPartnersListContactsQuery = z.object({
    include_archived: z.boolean().optional()
});

export const zPartnersListContactsResponse = zItemsContact;

export const zPartnersCreateContactBody = zContactBody;

export const zPartnersCreateContactPath = z.object({
    id: z.number().int()
});

export const zPartnersCreateContactResponse = zContact;

export const zPartnersUpdateContactBody = zContactBody;

export const zPartnersUpdateContactPath = z.object({
    id: z.number().int()
});

export const zPartnersUpdateContactResponse = zContact;

export const zPartnersArchiveContactPath = z.object({
    id: z.number().int()
});

/**
 * Archived
 */
export const zPartnersArchiveContactResponse = z.void();

export const zLeadsSearchQuery = z.object({
    q: z.string().optional(),
    stage: z.string().optional(),
    assigned_to: z.number().int().optional(),
    open: z.boolean().optional(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional()
});

export const zLeadsSearchResponse = zItemsLeadSummary;

export const zLeadsCreateBody = zLeadBody;

export const zLeadsCreateResponse = zLead;

export const zLeadsDetailPath = z.object({
    id: z.number().int()
});

export const zLeadsDetailResponse = zLeadDetail;

export const zLeadsUpdateBody = zLeadBody;

export const zLeadsUpdatePath = z.object({
    id: z.number().int()
});

export const zLeadsUpdateResponse = zLead;

export const zLeadsChangeStageBody = zStageBody;

export const zLeadsChangeStagePath = z.object({
    id: z.number().int()
});

export const zLeadsChangeStageResponse = zStageChange;

export const zLeadsTransitionsPath = z.object({
    id: z.number().int()
});

/**
 * Manual stage targets with note requirements; `won` is listed with `manual: false`
 */
export const zLeadsTransitionsResponse = zItemsTransitionOption;

/**
 * `partner_id` may be omitted when the lead has one; `title` defaults to the lead's.
 */
export const zLeadsConvertBody = zOrderBody;

export const zLeadsConvertPath = z.object({
    id: z.number().int()
});

export const zLeadsConvertResponse = zOrder;

export const zOrdersSearchQuery = z.object({
    q: z.string().optional(),
    stage: z.string().optional(),
    partner_id: z.number().int().optional(),
    project_type_id: z.number().int().optional(),
    assigned_to: z.number().int().optional(),
    open: z.boolean().optional(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional()
});

export const zOrdersSearchResponse = zItemsOrderSummary;

/**
 * `partner_id` and `title` are required.
 */
export const zOrdersCreateBody = zOrderBody;

export const zOrdersCreateResponse = zOrder;

export const zOrdersDetailPath = z.object({
    id: z.number().int()
});

export const zOrdersDetailResponse = zOrderDetail;

export const zOrdersUpdateBody = zPatchOrder;

export const zOrdersUpdatePath = z.object({
    id: z.number().int()
});

export const zOrdersUpdateResponse = zOrder;

export const zOrdersChangeStageBody = zStageBody;

export const zOrdersChangeStagePath = z.object({
    id: z.number().int()
});

export const zOrdersChangeStageResponse = zStageChange;

export const zOrdersTransitionsPath = z.object({
    id: z.number().int()
});

/**
 * Manual stage targets with note and gate requirements
 */
export const zOrdersTransitionsResponse = zItemsTransitionOption;

export const zOrdersStageHistoryPath = z.object({
    id: z.number().int()
});

/**
 * Stage history, oldest first
 */
export const zOrdersStageHistoryResponse = zItemsStageEntry;

export const zOrdersAuditTrailPath = z.object({
    id: z.number().int()
});

export const zOrdersAuditTrailQuery = z.object({
    limit: z.number().int().optional()
});

export const zOrdersAuditTrailResponse = zItemsAuditEntry;

export const zOrdersListItemsPath = z.object({
    id: z.number().int()
});

export const zOrdersListItemsResponse = zItemsItemView;

export const zOrdersAddItemBody = zAddItem;

export const zOrdersAddItemPath = z.object({
    id: z.number().int()
});

export const zOrdersAddItemResponse = zItemView;

export const zOrdersDeleteItemPath = z.object({
    id: z.number().int()
});

/**
 * Deleted
 */
export const zOrdersDeleteItemResponse = z.void();

export const zOrdersUpdateItemBody = zPatchItem;

export const zOrdersUpdateItemPath = z.object({
    id: z.number().int()
});

export const zOrdersUpdateItemResponse = zItemView;

export const zBlockersListOpenQuery = z.object({
    responsible_partner_id: z.number().int().optional(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional()
});

/**
 * Open blockers across all orders
 */
export const zBlockersListOpenResponse = zItemsBlocker;

export const zBlockersListForOrderPath = z.object({
    id: z.number().int()
});

export const zBlockersListForOrderResponse = zItemsBlocker;

export const zBlockersCreateBody = zBlockerBody;

export const zBlockersCreatePath = z.object({
    id: z.number().int()
});

export const zBlockersCreateResponse = zBlocker;

export const zBlockersUpdateBody = zBlockerBody;

export const zBlockersUpdatePath = z.object({
    id: z.number().int()
});

export const zBlockersUpdateResponse = zBlocker;

export const zBlockersResolveBody = zResolveBody;

export const zBlockersResolvePath = z.object({
    id: z.number().int()
});

export const zBlockersResolveResponse = zBlocker;

export const zBlockersReopenPath = z.object({
    id: z.number().int()
});

export const zBlockersReopenResponse = zBlocker;

export const zMediaRequestUploadBody = zUploadRequest;

export const zMediaRequestUploadPath = z.object({
    id: z.number().int()
});

export const zMediaRequestUploadResponse = zUploadResponse;

export const zMediaCompleteUploadBody = zCompleteBody;

/**
 * Already recorded
 */
export const zMediaCompleteUploadResponse = zCompleted;

export const zMediaListImagesPath = z.object({
    id: z.number().int()
});

export const zMediaListImagesQuery = z.object({
    category: zImageCategory.optional()
});

export const zMediaListImagesResponse = zItemsImageView;

export const zMediaOriginalUrlPath = z.object({
    id: z.number().int()
});

export const zMediaOriginalUrlResponse = zOriginalImageUrl;

export const zMediaDeleteImagePath = z.object({
    id: z.number().int()
});

/**
 * Deleted. Intake photos answer `409 immutable`.
 */
export const zMediaDeleteImageResponse = z.void();

export const zMediaListDocumentsPath = z.object({
    id: z.number().int()
});

export const zMediaListDocumentsResponse = zItemsDocument;

export const zMediaDocumentUrlPath = z.object({
    id: z.number().int()
});

export const zMediaDocumentUrlResponse = zDownloadUrl;

export const zMediaDeleteDocumentPath = z.object({
    id: z.number().int()
});

/**
 * Deleted
 */
export const zMediaDeleteDocumentResponse = z.void();

export const zMobileOrderPickerQuery = z.object({
    q: z.string().optional(),
    all: z.boolean().optional()
});

/**
 * Compact order picker; `Cache-Control: private, max-age=60`
 */
export const zMobileOrderPickerResponse = zItemsPickerOrder;

export const zEmailListQuery = z.object({
    order_id: z.number().int().optional(),
    lead_id: z.number().int().optional(),
    partner_id: z.number().int().optional(),
    status: zEmailStatus.optional(),
    attention: z.boolean().optional(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional()
});

export const zEmailListResponse = zItemsEmailSummary;

/**
 * Subject/body override the template. Unresolved variables are rejected.
 */
export const zEmailSendBody = zComposeRequest;

/**
 * Queued
 */
export const zEmailSendResponse = zEmailMessage;

export const zEmailPreviewBody = zComposeRequest;

export const zEmailPreviewResponse = zPreview;

export const zEmailDetailPath = z.object({
    id: z.number().int()
});

export const zEmailDetailResponse = zEmailMessage;

export const zEmailCancelPath = z.object({
    id: z.number().int()
});

/**
 * Cancelled
 */
export const zEmailCancelResponse = z.void();

export const zEmailRetryPath = z.object({
    id: z.number().int()
});

export const zEmailListTemplatesResponse = zItemsEmailTemplate;

export const zEmailCreateTemplateBody = zCreateTemplate;

export const zEmailCreateTemplateResponse = zEmailTemplate;

export const zEmailVariablesResponse = zItemsTemplateVariable;

export const zEmailUpdateTemplateBody = zPatchTemplate;

export const zEmailUpdateTemplatePath = z.object({
    id: z.number().int()
});

export const zEmailUpdateTemplateResponse = zEmailTemplate;

export const zEmailListSuppressionsResponse = zItemsSuppression;

export const zEmailAddSuppressionBody = zAddSuppression;

/**
 * Added
 */
export const zEmailAddSuppressionResponse = z.void();

export const zEmailRemoveSuppressionPath = z.object({
    email: z.string()
});

/**
 * Removed
 */
export const zEmailRemoveSuppressionResponse = z.void();

export const zReportsVolumeQuery = z.object({
    from: z.string().date().optional(),
    to: z.string().date().optional(),
    group: z.string().optional(),
    include_cancelled: z.boolean().optional()
});

export const zReportsVolumeResponse = zVolumeReport;

export const zReportsStageDurationsQuery = z.object({
    from: z.string().date().optional(),
    to: z.string().date().optional(),
    project_type_id: z.number().int().optional()
});

export const zReportsStageDurationsResponse = zDurationReport;

export const zReportsThroughputQuery = z.object({
    from: z.string().date().optional(),
    to: z.string().date().optional()
});

export const zReportsThroughputResponse = zThroughputReport;

/**
 * Open orders past their stage's `stall_after_days`
 */
export const zReportsStalledResponse = zItemsStalledOrder;

export const zReportsBlockerLoadQuery = z.object({
    from: z.string().date().optional(),
    to: z.string().date().optional()
});

export const zReportsBlockerLoadResponse = zBlockerLoadReport;

export const zReportsFxRatesQuery = z.object({
    base: z.string().optional(),
    from: z.string().date().optional(),
    to: z.string().date().optional()
});

/**
 * Stored MNB rates
 */
export const zReportsFxRatesResponse = zItemsFxRate;

export const zAdminStatusResponse = zAdminStatus;

export const zAdminListJobsQuery = z.object({
    state: z.string().optional(),
    limit: z.number().int().optional()
});

export const zAdminListJobsResponse = zItemsJob;

export const zAdminRetryJobPath = z.object({
    id: z.number().int()
});

export const zAdminFetchFxBody = zFxFetch;

export const zAdminFetchFxResponse = zJobQueued;

export const zAdminRunNowPath = z.object({
    kind: z.string()
});

export const zAdminRunNowResponse = zJobQueued;

export const zAdminTestEmailBody = zEmailTestBody;

export const zAdminTestEmailResponse = zEmailTestResult;
